- hosts: dev
  become: True
  tasks:
    - name: Start the container
      docker_container:
        name: helloapp
        image: "devopsforyou94/helloapp:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8090:8090
